# Generated by Django 3.1.3 on 2020-11-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.TextField(max_length=512, unique=True)),
                ('label', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('file_path', models.TextField()),
                ('indexed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(max_length=4096, unique=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.file')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureWeigth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.feature')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.file')),
            ],
        ),
    ]
